import time

def show_vir_das():
    height = 21
    width = 70

    print('Initializing Vir Das Sequence...')
    time.sleep(1)

    for row in range(height):
        line = ""
        for col in range(width):
            char = " "

            if row == 0:
                if 0 <= col <= 2: char = "+"
                elif 3 <= col <= 6: char = "="
                elif 7 <= col <= 14: char = "-"
                elif 15 <= col <= 21: char = ":"
                elif 22 <= col <= 25: char = "."
                elif col == 27: char = ":"
                elif col == 28: char = "="
                elif col == 29: char = "%"
                elif 30 <= col <= 31: char = "@"
                elif col == 32: char = "#"
                elif col == 33: char = "@"
                elif 34 <= col <= 36: char = "#"
                elif 37 <= col <= 40: char = "@"
                elif col == 41: char = "%"
                elif col == 42: char = "#"
                elif col == 43: char = "-"
                elif 44 <= col <= 46: char = "."
                elif 47 <= col <= 50: char = ":"
                elif 51 <= col <= 53: char = "-"
                elif 54 <= col <= 58: char = "="
                elif 59 <= col <= 62: char = "+"
                elif 63 <= col <= 66: char = "*"
                elif 67 <= col <= 69: char = "#"

            elif row == 1:
                if col == 0: char = "+"
                elif 1 <= col <= 5: char = "="
                elif 6 <= col <= 12: char = "-"
                elif 13 <= col <= 20: char = ":"
                elif 21 <= col <= 24: char = "."
                elif col == 26: char = "+"
                elif 27 <= col <= 29: char = "@"
                elif col == 30: char = "*"
                elif col == 31: char = "%"
                elif col == 32: char = "#"
                elif col == 33: char = "*"
                elif col == 34: char = "%"
                elif 35 <= col <= 36: char = "#"
                elif col == 37: char = "%"
                elif 38 <= col <= 43: char = "@"
                elif col == 44: char = "%"
                elif col == 45: char = ":"
                elif 46 <= col <= 48: char = "."
                elif 49 <= col <= 51: char = ":"
                elif 52 <= col <= 54: char = "-"
                elif 55 <= col <= 59: char = "="
                elif 60 <= col <= 64: char = "+"
                elif 65 <= col <= 67: char = "*"
                elif 68 <= col <= 69: char = "#"

            elif row == 2:
                if 0 <= col <= 3: char = "="
                elif 4 <= col <= 10: char = "-"
                elif 11 <= col <= 19: char = ":"
                elif 20 <= col <= 23: char = "."
                elif col == 25: char = "="
                elif col == 26: char = "@"
                elif col == 27: char = "%"
                elif 28 <= col <= 29: char = "#"
                elif 30 <= col <= 45: char = "@"
                elif 46 <= col <= 48: char = "."
                elif 49 <= col <= 51: char = ":"
                elif 52 <= col <= 55: char = "-"
                elif 56 <= col <= 61: char = "="
                elif 62 <= col <= 65: char = "+"
                elif 66 <= col <= 68: char = "*"
                elif col == 69: char = "#"
            elif row == 3:
                if 0 <= col <= 2: char = "="
                elif 3 <= col <= 8: char = "-"
                elif 9 <= col <= 18: char = ":"
                elif 19 <= col <= 25: char = "."
                elif col == 26: char = "="
                elif col == 27: char = "#"
                elif col == 28: char = "@"
                elif 29 <= col <= 31: char = "%"
                elif col == 32: char = "*"
                elif col == 33: char = "="
                elif col == 34: char = ":"
                elif 35 <= col <= 36: char = "-"
                elif 37 <= col <= 38: char = "+"
                elif col == 39: char = "*"
                elif 40 <= col <= 45: char = "@"
                elif col == 46: char = "="
                elif 47 <= col <= 49: char = "."
                elif 50 <= col <= 52: char = ":"
                elif 53 <= col <= 56: char = "-"
                elif 57 <= col <= 61: char = "="
                elif 62 <= col <= 65: char = "+"
                elif 66 <= col <= 68: char = "*"
                elif col == 69: char = "#"

            elif row == 4:
                if 0 <= col <= 2: char = "="
                elif 3 <= col <= 7: char = "-"
                elif 8 <= col <= 17: char = ":"
                elif 18 <= col <= 24: char = "."
                elif col == 26: char = "."
                elif col == 27: char = "@"
                elif col == 28: char = "#"
                elif col == 40: char = "."
                elif col == 41: char = "+"
                elif 42 <= col <= 45: char = "@"
                elif col == 46: char = "%"
                elif 47 <= col <= 50: char = "."
                elif 51 <= col <= 53: char = ":"
                elif 54 <= col <= 58: char = "-"
                elif 59 <= col <= 62: char = "="
                elif 63 <= col <= 66: char = "+"
                elif 67 <= col <= 68: char = "*"
                elif col == 69: char = "#"

            elif row == 5:
                if col == 0: char = "="
                elif 1 <= col <= 6: char = "-"
                elif 7 <= col <= 14: char = ":"
                elif 15 <= col <= 25: char = "."
                elif col == 26: char = ":"
                elif col == 27: char = "%"
                elif col == 40: char = ":"
                elif col == 41: char = "="
                elif 42 <= col <= 46: char = "@"
                elif 47 <= col <= 51: char = "."
                elif 52 <= col <= 53: char = ":"
                elif 54 <= col <= 58: char = "-"
                elif 59 <= col <= 63: char = "="
                elif 64 <= col <= 66: char = "+"
                elif 67 <= col <= 69: char = "*"

            elif row == 6:
                if 0 <= col <= 5: char = "-"
                elif 6 <= col <= 13: char = ":"
                elif 14 <= col <= 25: char = "."
                elif col == 26: char = ":"
                elif col == 27: char = "+"
                elif col == 36: char = "."
                elif 37 <= col <= 39: char = ":"
                elif col == 40: char = "-"
                elif col == 41: char = "+"
                elif 42 <= col <= 46: char = "@"
                elif 49 <= col <= 51: char = "."
                elif 52 <= col <= 54: char = ":"
                elif 55 <= col <= 59: char = "-"
                elif 60 <= col <= 64: char = "="
                elif 65 <= col <= 66: char = "+"
                elif 67 <= col <= 69: char = "*"
            elif row == 7:
                if 0 <= col <= 4: char = "-"
                elif 5 <= col <= 12: char = ":"
                elif 13 <= col <= 26: char = "."
                elif col == 27: char = ":"
                elif col == 28: char = "+"
                elif col == 29: char = "#"
                elif col == 30: char = "*"
                elif col == 31: char = "."
                elif col == 34: char = ":"
                elif 35 <= col <= 36: char = "#"
                elif 37 <= col <= 38: char = "*"
                elif col == 39: char = "+"
                elif 40 <= col <= 42: char = "*"
                elif 43 <= col <= 45: char = "@"
                elif col == 46: char = "%"
                elif col == 47: char = "."
                elif 49 <= col <= 51: char = "."
                elif 52 <= col <= 54: char = ":"
                elif 55 <= col <= 59: char = "-"
                elif 60 <= col <= 64: char = "="
                elif 65 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 8:
                if 0 <= col <= 3: char = "-"
                elif 4 <= col <= 12: char = ":"
                elif 13 <= col <= 27: char = "."
                elif col == 28: char = ":"
                elif col == 29: char = "+"
                elif col == 30: char = "="
                elif col == 31: char = "."
                elif 34 <= col <= 35: char = "-"
                elif col == 36: char = "."
                elif col == 37: char = "-"
                elif col == 38: char = "="
                elif col == 39: char = ":"
                elif col == 40: char = "."
                elif col == 41: char = "="
                elif col == 42: char = "+"
                elif 43 <= col <= 44: char = "@"
                elif 45 <= col <= 46: char = "#"
                elif col == 47: char = "+"
                elif 50 <= col <= 52: char = "."
                elif 53 <= col <= 55: char = ":"
                elif 56 <= col <= 59: char = "-"
                elif 60 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 9:
                if 0 <= col <= 3: char = "-"
                elif 4 <= col <= 11: char = ":"
                elif 12 <= col <= 27: char = "."
                elif 33 <= col <= 34: char = "."
                elif col == 41: char = ":"
                elif col == 42: char = "+"
                elif 43 <= col <= 44: char = "@"
                elif col == 45: char = "%"
                elif col == 46: char = "-"
                elif col == 47: char = ":"
                elif 51 <= col <= 52: char = "."
                elif 53 <= col <= 56: char = ":"
                elif 57 <= col <= 60: char = "-"
                elif 61 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 10:
                if 0 <= col <= 2: char = "-"
                elif 3 <= col <= 9: char = ":"
                elif 10 <= col <= 27: char = "."
                elif col == 33: char = "."
                elif col == 34: char = "-"
                elif col == 35: char = "+"
                elif col == 40: char = ":"
                elif col == 41: char = "="
                elif col == 42: char = "*"
                elif 43 <= col <= 44: char = "@"
                elif 45 <= col <= 46: char = "="
                elif col == 47: char = "+"
                elif 51 <= col <= 53: char = "."
                elif 54 <= col <= 56: char = ":"
                elif 57 <= col <= 59: char = "-"
                elif 60 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"
            elif row == 11:
                if 0 <= col <= 2: char = "-"
                elif 3 <= col <= 9: char = ":"
                elif 10 <= col <= 27: char = "."
                elif col == 31: char = "-"
                elif col == 32: char = "*"
                elif 33 <= col <= 35: char = "@"
                elif col == 36: char = "+"
                elif col == 37: char = ":"
                elif col == 39: char = "."
                elif 40 <= col <= 41: char = "="
                elif col == 42: char = "*"
                elif col == 43: char = "%"
                elif 44 <= col <= 48: char = "@"
                elif col == 49: char = "-"
                elif 52 <= col <= 53: char = "."
                elif 54 <= col <= 56: char = ":"
                elif 57 <= col <= 60: char = "-"
                elif 61 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 12:
                if 0 <= col <= 2: char = "-"
                elif 3 <= col <= 8: char = ":"
                elif 9 <= col <= 17: char = "."
                elif col == 20: char = "."
                elif 23 <= col <= 25: char = "."
                elif col == 28: char = "."
                elif col == 30: char = "="
                elif col == 31: char = "-"
                elif 32 <= col <= 33: char = "."
                elif col == 34: char = "-"
                elif 35 <= col <= 36: char = "="
                elif col == 37: char = "+"
                elif col == 38: char = "."
                elif col == 39: char = ":"
                elif col == 40: char = "="
                elif col == 41: char = "+"
                elif col == 42: char = "#"
                elif 43 <= col <= 48: char = "@"
                elif col == 49: char = "#"
                elif col == 50: char = "="
                elif col == 51: char = "."
                elif col == 53: char = "."
                elif 54 <= col <= 56: char = ":"
                elif 57 <= col <= 61: char = "-"
                elif 62 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 13:
                if 0 <= col <= 1: char = "-"
                elif 2 <= col <= 6: char = ":"
                elif 7 <= col <= 18: char = "."
                elif col == 22: char = "."
                elif col == 29: char = "+"
                elif col == 30: char = ":"
                elif col == 32: char = "."
                elif col == 33: char = "="
                elif col == 34: char = "+"
                elif col == 37: char = "-"
                elif col == 38: char = "+"
                elif col == 39: char = "*"
                elif col == 40: char = "#"
                elif 41 <= col <= 42: char = "@"
                elif col == 43: char = "#"
                elif 44 <= col <= 48: char = "@"
                elif col == 49: char = "*"
                elif col == 50: char = "="
                elif col == 51: char = "-"
                elif col == 52: char = ":"
                elif 53 <= col <= 54: char = "."
                elif 55 <= col <= 56: char = ":"
                elif 57 <= col <= 60: char = "-"
                elif 61 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"
            elif row == 14:
                if 0 <= col <= 1: char = "-"
                elif 2 <= col <= 7: char = ":"
                elif 8 <= col <= 20: char = "."
                elif col == 29: char = ":"
                elif col == 30: char = "*"
                elif 33 <= col <= 34: char = ":"
                elif col == 35: char = "."
                elif col == 36: char = "-"
                elif col == 37: char = "%"
                elif 38 <= col <= 40: char = "@"
                elif col == 41: char = "%"
                elif 42 <= col <= 43: char = "*"
                elif 44 <= col <= 46: char = "@"
                elif col == 47: char = "#"
                elif col == 48: char = "*"
                elif col == 49: char = "="
                elif col == 50: char = "-"
                elif 51 <= col <= 52: char = "."
                elif 53 <= col <= 56: char = ":"
                elif 57 <= col <= 62: char = "-"
                elif 63 <= col <= 65: char = "="
                elif 66 <= col <= 67: char = "+"
                elif 68 <= col <= 69: char = "*"

            elif row == 15:
                if col == 0: char = "-"
                elif 1 <= col <= 6: char = ":"
                elif 7 <= col <= 20: char = "."
                elif col == 29: char = "-"
                elif col == 30: char = "%"
                elif col == 31: char = "#"
                elif 32 <= col <= 35: char = "%"
                elif 36 <= col <= 37: char = "@"
                elif col == 38: char = "%"
                elif 39 <= col <= 40: char = "#"
                elif col == 41: char = "*"
                elif col == 42: char = "+"
                elif col == 43: char = "%"
                elif 44 <= col <= 45: char = "@"
                elif 46 <= col <= 47: char = "="
                elif col == 48: char = "-"
                elif col == 49: char = ":"
                elif 50 <= col <= 51: char = "."
                elif 54 <= col <= 58: char = ":"
                elif 59 <= col <= 63: char = "-"
                elif 64 <= col <= 65: char = "="
                elif 66 <= col <= 68: char = "+"
                elif col == 69: char = "*"

            elif row == 16:
                if 0 <= col <= 6: char = ":"
                elif 7 <= col <= 20: char = "."
                elif col == 28: char = "."
                elif col == 29: char = "*"
                elif col == 30: char = "@"
                elif col == 31: char = "."
                elif col == 32: char = ":"
                elif col == 33: char = "="
                elif col == 34: char = ":"
                elif col == 37: char = "."
                elif col == 38: char = ":"
                elif 39 <= col <= 40: char = "="
                elif col == 41: char = "+"
                elif col == 42: char = "#"
                elif 43 <= col <= 44: char = "@"
                elif col == 45: char = "#"
                elif col == 46: char = "."
                elif 47 <= col <= 48: char = ":"
                elif col == 49: char = "."
                elif col == 55: char = "."
                elif 56 <= col <= 59: char = ":"
                elif 60 <= col <= 63: char = "-"
                elif 64 <= col <= 65: char = "="
                elif 66 <= col <= 68: char = "+"
                elif col == 69: char = "*"
            elif row == 17:
                if 0 <= col <= 5: char = ":"
                elif 6 <= col <= 19: char = "."
                elif col == 28: char = "-"
                elif 29 <= col <= 30: char = "%"
                elif col == 31: char = ":"
                elif 33 <= col <= 34: char = "-"
                elif 35 <= col <= 36: char = ":"
                elif 38 <= col <= 39: char = "."
                elif col == 40: char = ":"
                elif col == 41: char = "#"
                elif 42 <= col <= 44: char = "%"
                elif col == 45: char = "@"
                elif col == 46: char = "."
                elif col == 56: char = "."
                elif col == 57: char = "*"
                elif col == 58: char = "="
                elif 59 <= col <= 61: char = ":"
                elif 62 <= col <= 64: char = "-"
                elif 65 <= col <= 66: char = "="
                elif 67 <= col <= 69: char = "+"

            elif row == 18:
                if 0 <= col <= 5: char = ":"
                elif 6 <= col <= 16: char = "."
                elif 28 <= col <= 30: char = "+"
                elif col == 31: char = "*"
                elif col == 32: char = ":"
                elif col == 35: char = "="
                elif 36 <= col <= 37: char = "#"
                elif col == 38: char = "@"
                elif col == 39: char = "+"
                elif col == 40: char = "="
                elif 41 <= col <= 42: char = "@"
                elif col == 43: char = "*"
                elif col == 44: char = "#"
                elif col == 45: char = "%"
                elif col == 46: char = ":"
                elif col == 53: char = "."
                elif col == 54: char = "="
                elif col == 55: char = "%"
                elif 56 <= col <= 58: char = "@"
                elif col == 59: char = "#"
                elif col == 60: char = "*"
                elif col == 61: char = "="
                elif 62 <= col <= 63: char = ":"
                elif col == 64: char = "-"
                elif 65 <= col <= 66: char = "="
                elif 67 <= col <= 69: char = "+"

            elif row == 19:
                if 0 <= col <= 4: char = ":"
                elif 5 <= col <= 13: char = "."
                elif col == 28: char = "#"
                elif 29 <= col <= 30: char = "="
                elif col == 31: char = "+"
                elif col == 32: char = "="
                elif col == 33: char = "."
                elif col == 34: char = "-"
                elif col == 35: char = "@"
                elif col == 36: char = "*"
                elif col == 37: char = "#"
                elif col == 38: char = "-"
                elif col == 39: char = "%"
                elif col == 40: char = "@"
                elif col == 41: char = "*"
                elif col == 42: char = "-"
                elif col == 43: char = "#"
                elif col == 44: char = "@"
                elif col == 45: char = "-"
                elif col == 46: char = "="
                elif col == 49: char = "."
                elif col == 50: char = "+"
                elif 51 <= col <= 61: char = "@"
                elif col == 62: char = "#"
                elif col == 63: char = ":"
                elif 64 <= col <= 65: char = "-"
                elif 66 <= col <= 67: char = "="
                elif 68 <= col <= 69: char = "+"
            elif row == 20:
                if 0 <= col <= 4: char = ":"
                elif 5 <= col <= 12: char = "."
                elif col == 28: char = "#"
                elif col == 29: char = "*"
                elif col == 30: char = ":"
                elif col == 31: char = "-"
                elif col == 32: char = "."
                elif col == 34: char = "+"
                elif col == 35: char = "="
                elif col == 37: char = "-"
                elif col == 39: char = "+"
                elif col == 40: char = "*"
                elif col == 41: char = "="
                elif col == 42: char = "."
                elif col == 43: char = "#"
                elif col == 44: char = "*"
                elif col == 45: char = "%"
                elif col == 46: char = "-"
                elif col == 49: char = "="
                elif 50 <= col <= 62: char = "@"
                elif col == 63: char = "+"
                elif col == 64: char = ":"
                elif 65 <= col <= 66: char = "-"
                elif col == 67: char = "="
                elif 68 <= col <= 69: char = "+"

            line += char
        print(line)
        time.sleep(0.04)

if __name__ == "__main__":
    show_vir_das()
